export const API_ENDPOINTS = {
  HEALTH: '/health',
  AUTH: {
    CUSTOMER_REGISTER: '/auth/customer/register',
    CUSTOMER_LOGIN: '/auth/customer/login',
    ADMIN_LOGIN: '/auth/admin/login',
    ME: '/auth/me',
    LOGOUT: '/auth/logout',
  },
  CUSTOMERS: {
    PROFILE: '/customer/profile',
    UPDATE: '/customer/profile',
    LIST: '/admin/customers',
    DETAIL: (id: string) => `/admin/customers/${id}`,
  },
  CUSTOMER_DOCS: {
    LIST: '/customer/documents',
    UPLOAD: '/customer/documents',
    DETAIL: (id: string) => `/customer/documents/${id}`,
    FILE: (id: string) => `/customer/documents/${id}/file`,
    REUPLOAD: (id: string) => `/customer/documents/${id}/reupload`,
  },
  ADMIN: {
    STATUS: '/admin/status',
    KYC_LIST: '/admin/kyc',
    KYC_DETAIL: (id: string) => `/admin/kyc/${id}`,
    REVIEW_DOCUMENT: (id: string) => `/admin/kyc/documents/${id}/review`,
    DOCUMENT_FILE: (id: string) => `/admin/kyc/documents/${id}/file`,
    REQUEST_DOCUMENT: (id: string) => `/admin/kyc/${id}/request-document`,
    KYC_DECISION: (id: string) => `/admin/kyc/${id}/decision`,
  },
  LOANS: {
    CUSTOMER_APPLY: '/customer/loan-applications',
    CUSTOMER_LIST: '/customer/loan-applications',
    CUSTOMER_DETAIL: (id: string) => `/customer/loan-applications/${id}`,
    ACCEPT_OFFER: (id: string) => `/customer/loan-applications/${id}/offer/accept`,
    REJECT_OFFER: (id: string) => `/customer/loan-applications/${id}/offer/reject`,
  },
  ADMIN_LOANS: {
    LIST: '/admin/loan-applications',
    DETAIL: (id: string) => `/admin/loan-applications/${id}`,
    REVIEW: (id: string) => `/admin/loan-applications/${id}/review`,
    REQUEST_DOCUMENTS: (id: string) => `/admin/loan-applications/${id}/request-documents`,
    HOLD: (id: string) => `/admin/loan-applications/${id}/hold`,
    REJECT: (id: string) => `/admin/loan-applications/${id}/reject`,
    APPROVE: (id: string) => `/admin/loan-applications/${id}/approve`,
    MODIFY_AMOUNT: (id: string) => `/admin/loan-applications/${id}/modify-amount`,
  },
  DOCUMENTS: {
    UPLOAD: '/documents/upload',
    LIST: '/documents',
    REVIEW: (id: string) => `/admin/documents/${id}/review`,
  },
  PAYMENTS: {
    CUSTOMER_REQUIREMENT: (loanId: string) => `/customer/payments/${loanId}`,
    SUBMIT_UTR: (loanId: string) => `/customer/payments/${loanId}/submit-utr`,
    ADMIN_LIST: '/admin/payments',
    VERIFY: (id: string) => `/admin/payments/${id}/verify`,
    REJECT: (id: string) => `/admin/payments/${id}/reject`,
  },
  AGREEMENTS: {
    CUSTOMER_GET: (id: string) => `/customer/loans/${id}/agreement`,
    CUSTOMER_ACCEPT: (id: string) => `/customer/loans/${id}/agreement/accept`,
    ADMIN_GET: (id: string) => `/admin/loans/${id}/agreement`,
  },
  DISBURSEMENTS: {
    CUSTOMER_GET: (loanId: string) => `/customer/loans/${loanId}/disbursement`,
    ADMIN_LIST: '/admin/disbursements',
    ADMIN_RECORD: '/admin/disbursements',
  },
  DASHBOARD: {
    ADMIN: '/admin/dashboard',
    CUSTOMER: '/customer/dashboard',
  },
  NOTIFICATIONS: {
    CUSTOMER_LIST: '/customer/notifications',
    CUSTOMER_MARK_READ: (id: string) => `/customer/notifications/${id}/read`,
    CUSTOMER_READ_ALL: '/customer/notifications/read-all',
    ADMIN_LIST: '/admin/notifications',
    ADMIN_MARK_READ: (id: string) => `/admin/notifications/${id}/read`,
  },
  REPORTS: {
    SUMMARY: '/admin/reports/summary',
    EXPORT_EXCEL: (type: string) => `/admin/reports/export/excel?type=${type}`,
  },
  SETTINGS: {
    PUBLIC_CONFIG: '/public/config',
    BRANDING_GET: '/admin/settings/branding',
    BRANDING_UPDATE: '/admin/settings/branding',
    EMAIL_GET: '/admin/settings/email',
    EMAIL_UPDATE: '/admin/settings/email',
    EMAIL_TEST: '/admin/settings/email/test',
    WHATSAPP_GET: '/admin/settings/whatsapp',
    WHATSAPP_UPDATE: '/admin/settings/whatsapp',
    WHATSAPP_TEST: '/admin/settings/whatsapp/test',
    PAYMENT_GET: '/admin/settings/payment',
    PAYMENT_UPDATE: '/admin/settings/payment',
  },
  AUDIT: {
    LIST: '/admin/audit-logs',
  },
  SUPPORT: {
    CUSTOMER_CREATE: '/customer/support/tickets',
    CUSTOMER_LIST: '/customer/support/tickets',
    ADMIN_LIST: '/admin/support/tickets',
    ADMIN_REPLY: (id: string) => `/admin/support/tickets/${id}/reply`,
  },
};

