export const API_ENDPOINTS = {
  HEALTH: '/health',
  AUTH: {
    CUSTOMER_REGISTER: '/auth/customer/register',
    CUSTOMER_LOGIN: '/auth/customer/login',
    ADMIN_LOGIN: '/auth/admin/login',
    ME: '/auth/me',
    LOGOUT: '/auth/logout',
  },
  CUSTOMERS: {
    PROFILE: '/customer/profile',
    UPDATE: '/customer/profile',
    LIST: '/admin/customers',
    DETAIL: (id: string) => `/admin/customers/${id}`,
    STATES: '/admin/customers/states',
    EXPORT: '/admin/customers/export',
    WHATSAPP_PENDING: (id: string) => `/admin/customers/${id}/whatsapp/pending`,
    WHATSAPP_HISTORY: (id: string) => `/admin/customers/${id}/whatsapp/history`,
    INVOICE_PDF: (id: string) => `/admin/customers/${id}/invoice/pdf`,
    APPROVAL_LETTER_PDF: (id: string) => `/admin/customers/${id}/approval-letter/pdf`,
  },
  CUSTOMER_DOCS: {
    LIST: '/customer/documents',
    UPLOAD: '/customer/documents',
    DETAIL: (id: string) => `/customer/documents/${id}`,
    FILE: (id: string) => `/customer/documents/${id}/file`,
    REUPLOAD: (id: string) => `/customer/documents/${id}/reupload`,
    SUBMIT_KYC: '/customer/kyc/submit',
  },
  ADMIN: {
    STATUS: '/admin/status',
    KYC_LIST: '/admin/kyc',
    KYC_DETAIL: (id: string) => `/admin/kyc/${id}`,
    REVIEW_DOCUMENT: (id: string) => `/admin/kyc/documents/${id}/review`,
    DOCUMENT_FILE: (id: string) => `/admin/kyc/documents/${id}/file`,
    REQUEST_DOCUMENT: (id: string) => `/admin/kyc/${id}/request-document`,
    KYC_DECISION: (id: string) => `/admin/kyc/${id}/decision`,
  },
  LOANS: {
    CUSTOMER_APPLY: '/customer/loan-applications',
    CUSTOMER_LIST: '/customer/loan-applications',
    CUSTOMER_DETAIL: (id: string) => `/customer/loan-applications/${id}`,
    ACCEPT_OFFER: (id: string) => `/customer/loan-applications/${id}/offer/accept`,
    REJECT_OFFER: (id: string) => `/customer/loan-applications/${id}/offer/reject`,
  },
  ADMIN_LOANS: {
    LIST: '/admin/loan-applications',
    DETAIL: (id: string) => `/admin/loan-applications/${id}`,
    REVIEW: (id: string) => `/admin/loan-applications/${id}/review`,
    REQUEST_DOCUMENTS: (id: string) => `/admin/loan-applications/${id}/request-documents`,
    HOLD: (id: string) => `/admin/loan-applications/${id}/hold`,
    REJECT: (id: string) => `/admin/loan-applications/${id}/reject`,
    APPROVE: (id: string) => `/admin/loan-applications/${id}/approve`,
    MODIFY_AMOUNT: (id: string) => `/admin/loan-applications/${id}/modify-amount`,
  },
  DOCUMENTS: {
    CUSTOMER_LIST: (customerId: string) => `/admin/customers/${customerId}/documents`,
    DOWNLOAD_ZIP: (customerId: string) => `/admin/customers/${customerId}/documents/download-zip`,
    DOWNLOAD_ALL: (customerId: string) => `/admin/customers/${customerId}/documents/download-all`,
    METADATA: (documentId: string) => `/admin/documents/${documentId}`,
    VIEW: (documentId: string) => `/admin/documents/${documentId}/view`,
    DOWNLOAD: (documentId: string) => `/admin/documents/${documentId}/download`,
    VERIFY: (documentId: string) => `/admin/documents/${documentId}/verify`,
    REJECT: (documentId: string) => `/admin/documents/${documentId}/reject`,
    REQUEST_CORRECTION: (documentId: string) => `/admin/documents/${documentId}/request-correction`,
  },
  PAYMENTS: {
    CUSTOMER_REQUIREMENT: (loanId: string) => `/customer/payments/${loanId}`,
    SUBMIT_UTR: (loanId: string) => `/customer/payments/${loanId}/submit-utr`,
    ADMIN_LIST: '/admin/payments',
    VERIFY: (id: string) => `/admin/payments/${id}/verify`,
    REJECT: (id: string) => `/admin/payments/${id}/reject`,
  },
  AGREEMENTS: {
    CUSTOMER_GET: (id: string) => `/customer/loans/${id}/agreement`,
    CUSTOMER_ACCEPT: (id: string) => `/customer/loans/${id}/agreement/accept`,
    ADMIN_GET: (id: string) => `/admin/loans/${id}/agreement`,
  },
  DISBURSEMENTS: {
    CUSTOMER_GET: (loanId: string) => `/customer/loans/${loanId}/disbursement`,
    ADMIN_LIST: '/admin/disbursements',
    ADMIN_RECORD: '/admin/disbursements',
  },
  DASHBOARD: {
    ADMIN: '/admin/dashboard',
    CUSTOMER: '/customer/dashboard',
  },
  NOTIFICATIONS: {
    CUSTOMER_LIST: '/customer/notifications',
    CUSTOMER_MARK_READ: (id: string) => `/customer/notifications/${id}/read`,
    CUSTOMER_READ_ALL: '/customer/notifications/read-all',
    ADMIN_LIST: '/admin/notifications',
    ADMIN_MARK_READ: (id: string) => `/admin/notifications/${id}/read`,
  },
  REPORTS: {
    SUMMARY: '/admin/reports/summary',
    EXPORT_EXCEL: (type: string) => `/admin/reports/export/excel?type=${type}`,
  },
  SETTINGS: {
    PUBLIC_CONFIG: '/public/config',
    BRANDING_GET: '/admin/settings/branding',
    BRANDING_UPDATE: '/admin/settings/branding',
    BRANDING_UPLOAD_LOGO: '/admin/settings/branding/upload-logo',
    BRANDING_UPLOAD_SECONDARY_LOGO: '/admin/settings/branding/upload-secondary-logo',
    BRANDING_UPLOAD_APPROVAL_HEADER: '/admin/settings/branding/upload-approval-header',
    BRANDING_UPLOAD_WATERMARK_LOGO: '/admin/settings/branding/upload-watermark-logo',
    BRANDING_UPLOAD_FAVICON: '/admin/settings/branding/upload-favicon',
    DOCUMENT_BRANDING_GET: '/admin/settings/document-branding',
    DOCUMENT_BRANDING_UPDATE: '/admin/settings/document-branding',
    PREVIEW_APPROVAL_LETTER: '/admin/settings/preview/approval-letter',
    PREVIEW_INVOICE: '/admin/settings/preview/invoice',
    EMAIL_GET: '/admin/settings/email',
    EMAIL_UPDATE: '/admin/settings/email',
    EMAIL_TEST: '/admin/settings/email/test',
    WHATSAPP_GET: '/admin/settings/whatsapp',
    WHATSAPP_UPDATE: '/admin/settings/whatsapp',
    WHATSAPP_TEST: '/admin/settings/whatsapp/test',
    PAYMENT_GET: '/admin/settings/payment',
    PAYMENT_UPDATE: '/admin/settings/payment',
  },
  AUDIT: {
    LIST: '/admin/audit-logs',
  },
  SUPPORT: {
    CUSTOMER_CREATE: '/customer/support/tickets',
    CUSTOMER_LIST: '/customer/support/tickets',
    ADMIN_LIST: '/admin/support/tickets',
    ADMIN_REPLY: (id: string) => `/admin/support/tickets/${id}/reply`,
  },
  DOMAINS: {
    LIST: '/admin/domains',
    CREATE: '/admin/domains',
    UPDATE: (id: string) => `/admin/domains/${id}`,
    DELETE: (id: string) => `/admin/domains/${id}`,
    PUBLIC_CONFIG: (host?: string) => `/public/domain-config${host ? `?host=${host}` : ''}`,
  },
  PAYMENT_METHODS: {
    GET: '/admin/settings/payment-methods',
    UPDATE: '/admin/settings/payment-methods',
  },
  UPI_SETTINGS: {
    GET: '/admin/settings/upi',
    UPDATE: '/admin/settings/upi',
    UPLOAD_QR: '/admin/settings/upi/upload-qr',
  },
  BANK_SETTINGS: {
    GET: '/admin/settings/bank',
    UPDATE: '/admin/settings/bank',
  },
  PAYMENT_LINKS: {
    LIST: '/admin/settings/payment-links',
    CREATE: '/admin/settings/payment-links',
    UPDATE: (id: string) => `/admin/settings/payment-links/${id}`,
    DELETE: (id: string) => `/admin/settings/payment-links/${id}`,
  },
  CHARGES: {
    LIST: '/admin/charges',
    CONFIG: '/admin/charges/config',
    RECORDS: '/admin/charges/records',
    INVOICE: (id: string, download = false) => `/admin/charges/records/${id}/invoice${download ? '?download=true' : ''}`,
    CREATE: '/admin/charges',
    UPDATE: (id: string) => `/admin/charges/${id}`,
    DELETE: (id: string) => `/admin/charges/${id}`,
    SPECIFIC: {
      LIST: (params?: { customerId?: string; applicationId?: string }) =>
        `/admin/charges/specific?${new URLSearchParams(params as any).toString()}`,
      BY_APPLICATION: (appId: string) => `/admin/charges/specific/application/${appId}`,
      BY_CUSTOMER: (custId: string) => `/admin/charges/specific/customer/${custId}`,
      CREATE: '/admin/charges/specific',
      SEND_ALL: '/admin/charges/specific/send-all',
      SEND: (id: string) => `/admin/charges/specific/${id}/send`,
      UPDATE: (id: string) => `/admin/charges/specific/${id}`,
      CANCEL: (id: string) => `/admin/charges/specific/${id}/cancel`,
      REMIND: (id: string) => `/admin/charges/specific/${id}/remind`,
      INVOICE: (id: string, download = false) => `/admin/charges/specific/${id}/invoice${download ? '?download=true' : ''}`,
      VERIFY_PAYMENT: (id: string) => `/admin/charges/specific/${id}/verify-payment`,
    },
  },
  CUSTOMER_CHARGES: {
    LIST: '/customer/charges',
    BY_APPLICATION: (appId: string) => `/customer/charges/application/${appId}`,
    GET: (id: string) => `/customer/charges/${id}`,
    SUBMIT_UTR: (id: string) => `/customer/charges/${id}/submit-utr`,
    INVOICE: (id: string, download = false) => `/customer/charges/${id}/invoice${download ? '?download=true' : ''}`,
  },
  ADMIN_USERS: {
    LIST: '/admin/users',
    CREATE: '/admin/users',
    UPDATE: (id: string) => `/admin/users/${id}`,
  },
  VERIFICATION: {
    VERIFY_DOCUMENT: (token: string) => `/public/verify/document/${token}`,
  },
  ACTIVE_PAYMENT_OPTIONS: '/public/payments/options',
  EMI_SCHEDULE: {
    GET: (id: string) => `/customer/loans/${id}/emi`,
    DOWNLOAD_PDF: (id: string) => `/customer/loans/${id}/emi-pdf`,
  },
  PDF: {
    APPROVAL_LETTER: (id: string) => `/approval-letter/${id}/pdf`,
    RECEIPT: (id: string) => `/customer/payments/${id}/receipt-pdf`,
  },
  COMMUNICATION: {
    CUSTOMERS: '/admin/communication/customers',
    TEMPLATES: '/admin/communication/templates',
    SEND_EMAIL: '/admin/communication/email',
    HISTORY: '/admin/communication/history',
    CUSTOMER_HISTORY: (customerId: string) => `/admin/communication/history/customer/${customerId}`,
  },
};

